[package]
name = "tinyshark"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = "4.5.48"
directories = "6.0.0"
pcap = "2.3.0"
serde = "1.0.226"
serde_json = "1.0.145"
